version: "3.9"

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./project/static:/app/project/static
      - ./project/templates:/app/project/templates
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
